language: elixir
elixir:
  - 1.5.3
otp_release:
  - 20.0

services:
  - postgresql

env:
  - DB_HOST=localhost MIX_ENV=test

before_script:
  - psql -c "CREATE DATABASE demo;" -U postgres
  - psql -c "CREATE USER demo WITH PASSWORD 'pass';" -U postgres
  - psql -c "ALTER USER demo CREATEDB;" -U postgres
  - psql -c "grant all privileges on database demo to demo;" -U postgres
  - mix ecto.migrate
