version: '2'
services:
  web:
    build:
      context: ../
      dockerfile: ./docker/dev/Dockerfile
    hostname: "web.ex_debug_toolbar_demo.docker"
    expose:
      - 4000
    depends_on:
      - postgresql
    volumes:
      - "../:${PWD}"
      - "/etc/localtime:/etc/localtime"
      - "historyData:/home/dev/history"
      - "${HOME}/.npm:/home/dev/.npm"
      - "${HOME}/.zshrc:/home/dev/.zshrc"
    networks:
      - backend
    working_dir: ${PWD}
    environment:
      HISTFILE: /home/dev/history/.zsh_history
      VIRTUAL_HOST: "web.ex_debug_toolbar_demo.docker"

  postgresql:
    image: postgres:9.6
    volumes:
      - postgresqlData:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: demo
      POSTGRES_DB: demo

networks:
  backend:
    driver: bridge

volumes:
  postgresqlData:
    external: false
  historyData:
    external: false
